// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/background.js"
    | "/icons/icon128.png"
    | "/icons/icon16.png"
    | "/icons/icon32.png"
    | "/icons/icon48.png"
    | "/options.html"
    | "/popup.html"
    | "/sidepanel.html"
    | "/wasm/doc_engine_bg.wasm"
    | "/wasm/doc_engine.js"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
