//! Builtin macro rules for common LaTeX commands.

use super::{MacroRule, RuleOutput};

/// Returns all builtin macro rules.
pub fn builtin_rules() -> Vec<MacroRule> {
    vec![
        // ── Font commands (inline text) ─────────────────────────────────
        MacroRule {
            id: "textbf".into(),
            name: "textbf".into(),
            arity: 1,
            output: RuleOutput::InlineText { content_arg: 0 },
            description: Some("Bold text".into()),
        },
        MacroRule {
            id: "textit".into(),
            name: "textit".into(),
            arity: 1,
            output: RuleOutput::InlineText { content_arg: 0 },
            description: Some("Italic text".into()),
        },
        MacroRule {
            id: "texttt".into(),
            name: "texttt".into(),
            arity: 1,
            output: RuleOutput::InlineText { content_arg: 0 },
            description: Some("Typewriter/monospace text".into()),
        },
        MacroRule {
            id: "textsf".into(),
            name: "textsf".into(),
            arity: 1,
            output: RuleOutput::InlineText { content_arg: 0 },
            description: Some("Sans-serif text".into()),
        },
        MacroRule {
            id: "emph".into(),
            name: "emph".into(),
            arity: 1,
            output: RuleOutput::InlineText { content_arg: 0 },
            description: Some("Emphasized text".into()),
        },
        MacroRule {
            id: "mathbf".into(),
            name: "mathbf".into(),
            arity: 1,
            output: RuleOutput::InlineText { content_arg: 0 },
            description: Some("Bold math text".into()),
        },
        MacroRule {
            id: "mathrm".into(),
            name: "mathrm".into(),
            arity: 1,
            output: RuleOutput::InlineText { content_arg: 0 },
            description: Some("Roman (upright) math text".into()),
        },
        MacroRule {
            id: "mathsf".into(),
            name: "mathsf".into(),
            arity: 1,
            output: RuleOutput::InlineText { content_arg: 0 },
            description: Some("Sans-serif math text".into()),
        },
        MacroRule {
            id: "mathtt".into(),
            name: "mathtt".into(),
            arity: 1,
            output: RuleOutput::InlineText { content_arg: 0 },
            description: Some("Typewriter math text".into()),
        },
        // ── Font size commands ──────────────────────────────────────────
        MacroRule {
            id: "tiny".into(),
            name: "tiny".into(),
            arity: 0,
            output: RuleOutput::Ignore,
            description: Some("Tiny font size".into()),
        },
        MacroRule {
            id: "small".into(),
            name: "small".into(),
            arity: 0,
            output: RuleOutput::Ignore,
            description: Some("Small font size".into()),
        },
        MacroRule {
            id: "large".into(),
            name: "large".into(),
            arity: 0,
            output: RuleOutput::Ignore,
            description: Some("Large font size".into()),
        },
        MacroRule {
            id: "Large".into(),
            name: "Large".into(),
            arity: 0,
            output: RuleOutput::Ignore,
            description: Some("Large font size".into()),
        },
        MacroRule {
            id: "LARGE".into(),
            name: "LARGE".into(),
            arity: 0,
            output: RuleOutput::Ignore,
            description: Some("LARGE font size".into()),
        },
        MacroRule {
            id: "huge".into(),
            name: "huge".into(),
            arity: 0,
            output: RuleOutput::Ignore,
            description: Some("Huge font size".into()),
        },
        MacroRule {
            id: "Huge".into(),
            name: "Huge".into(),
            arity: 0,
            output: RuleOutput::Ignore,
            description: Some("Huge font size".into()),
        },
        // ── Spacing commands ───────────────────────────────────────────
        MacroRule {
            id: "hspace".into(),
            name: "hspace".into(),
            arity: 1,
            output: RuleOutput::Ignore,
            description: Some("Horizontal spacing".into()),
        },
        MacroRule {
            id: "vspace".into(),
            name: "vspace".into(),
            arity: 1,
            output: RuleOutput::Ignore,
            description: Some("Vertical spacing".into()),
        },
        MacroRule {
            id: "quad".into(),
            name: "quad".into(),
            arity: 0,
            output: RuleOutput::Ignore,
            description: Some("1em quad spacing".into()),
        },
        MacroRule {
            id: "qquad".into(),
            name: "qquad".into(),
            arity: 0,
            output: RuleOutput::Ignore,
            description: Some("2em quad spacing".into()),
        },
        MacroRule {
            id: "smallskip".into(),
            name: "smallskip".into(),
            arity: 0,
            output: RuleOutput::Ignore,
            description: Some("Small vertical skip".into()),
        },
        MacroRule {
            id: "medskip".into(),
            name: "medskip".into(),
            arity: 0,
            output: RuleOutput::Ignore,
            description: Some("Medium vertical skip".into()),
        },
        MacroRule {
            id: "bigskip".into(),
            name: "bigskip".into(),
            arity: 0,
            output: RuleOutput::Ignore,
            description: Some("Big vertical skip".into()),
        },
        MacroRule {
            id: "newline".into(),
            name: "newline".into(),
            arity: 0,
            output: RuleOutput::Ignore,
            description: Some("Line break".into()),
        },
        MacroRule {
            id: "newpage".into(),
            name: "newpage".into(),
            arity: 0,
            output: RuleOutput::Ignore,
            description: Some("Page break".into()),
        },
        MacroRule {
            id: "pagebreak".into(),
            name: "pagebreak".into(),
            arity: 0,
            output: RuleOutput::Ignore,
            description: Some("Page break".into()),
        },
        MacroRule {
            id: "nopagebreak".into(),
            name: "nopagebreak".into(),
            arity: 0,
            output: RuleOutput::Ignore,
            description: Some("Suppress page break".into()),
        },
        MacroRule {
            id: "clearpage".into(),
            name: "clearpage".into(),
            arity: 0,
            output: RuleOutput::Ignore,
            description: Some("Clear all pending floats and page break".into()),
        },
        MacroRule {
            id: "cleardoublepage".into(),
            name: "cleardoublepage".into(),
            arity: 0,
            output: RuleOutput::Ignore,
            description: Some("Clear floats and go to next odd page".into()),
        },
        // ── Accents / symbols ──────────────────────────────────────────
        MacroRule {
            id: "underline".into(),
            name: "underline".into(),
            arity: 1,
            output: RuleOutput::InlineText { content_arg: 0 },
            description: Some("Underlined text".into()),
        },
        MacroRule {
            id: "sout".into(),
            name: "sout".into(),
            arity: 1,
            output: RuleOutput::InlineText { content_arg: 0 },
            description: Some("Strikethrough text (ulem)".into()),
        },
        MacroRule {
            id: "xout".into(),
            name: "xout".into(),
            arity: 1,
            output: RuleOutput::InlineText { content_arg: 0 },
            description: Some("Crossed-out text (ulem)".into()),
        },
        MacroRule {
            id: "uwave".into(),
            name: "uwave".into(),
            arity: 1,
            output: RuleOutput::InlineText { content_arg: 0 },
            description: Some("Wave underline (ulem)".into()),
        },
        MacroRule {
            id: "CJKfamily".into(),
            name: "CJKfamily".into(),
            arity: 1,
            output: RuleOutput::InlineText { content_arg: 0 },
            description: Some("CJK font family switch".into()),
        },
        MacroRule {
            id: "CJKunderline".into(),
            name: "CJKunderline".into(),
            arity: 1,
            output: RuleOutput::InlineText { content_arg: 0 },
            description: Some("CJK underline".into()),
        },
        MacroRule {
            id: "paragraph".into(),
            name: "paragraph".into(),
            arity: 1,
            output: RuleOutput::Heading { level: 4, text_arg: 0 },
            description: Some("Fourth-level heading".into()),
        },
        MacroRule {
            id: "subparagraph".into(),
            name: "subparagraph".into(),
            arity: 1,
            output: RuleOutput::Heading { level: 5, text_arg: 0 },
            description: Some("Fifth-level heading".into()),
        },
    ]
}
