param(
    [string]$Version = "v12",
    [string]$Zip = ""
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

. "$PSScriptRoot\_build_common.ps1"

$Root = Get-RepoRoot -ScriptDirectory $PSScriptRoot
$VersionTag = Get-VersionTag -Version $Version
$VersionNumber = Get-VersionNumber -Version $Version
$Paper3Dir = Join-Path $Root "examples\paper3"
$LatexDir = Join-Path $Paper3Dir "latex"
$MainTex = Join-Path $LatexDir "main-jos.tex"
if ([string]::IsNullOrWhiteSpace($Zip)) {
    $Zip = Join-Path $Paper3Dir "upload.zip"
}
$OutDir = Join-Path $Paper3Dir "output\to-docx"
$Stamp = Get-TimeStamp
$Base = "$VersionTag-论文稿件-jos-$Stamp"
$RustDocx = Join-Path $OutDir "$Base-rust.docx"
$DocxTool = Get-DocEnginePath -Root $Root

New-Item -ItemType Directory -Path $OutDir -Force | Out-Null

Write-Host "=== generating sh DOCX (delegated to scripts/build_docx.ps1) ==="
$buildStart = Get-Date
& (Join-Path $Root "scripts\build_docx.ps1") -Version $VersionNumber

$ShDocx = Get-LatestFile -Directory $OutDir -Filter "v$VersionNumber-论文稿件-jos-sh-*.docx" -After $buildStart
if (-not $ShDocx) {
    $ShDocx = Get-LatestFile -Directory $OutDir -Filter "v$VersionNumber-论文稿件-jos-sh-*.docx"
}
if (-not $ShDocx -or -not (Test-Path -LiteralPath $ShDocx)) {
    throw "sh DOCX not generated by build_docx.ps1"
}
Write-Host "OK $(Split-Path -Leaf $ShDocx) (via build_docx.ps1)"

if (-not (Test-Path -LiteralPath $Zip)) {
    Write-Host "=== zip not found; building upload.zip from $MainTex ==="
    Assert-PathExists -Path $MainTex -Kind "main tex"
    $Zip = Join-Path $Paper3Dir "upload.zip"
    New-Paper3UploadZip -Paper3Directory $Paper3Dir -LatexDirectory $LatexDir -MainTex $MainTex -OutputZip $Zip
}

Assert-Command -Name "cargo" -Hint "needed to build doc-engine for rust DOCX"

if (-not (Test-Path -LiteralPath $DocxTool)) {
    Write-Host "=== building doc-engine (release) ==="
    Invoke-Native -FilePath "cargo" -Arguments @("build", "--release", "-p", "doc-engine") -WorkingDirectory $Root
}
if (-not (Test-Path -LiteralPath $DocxTool)) {
    throw "missing tool: $DocxTool"
}

Write-Host "=== generating rust DOCX ==="
Invoke-Native -FilePath $DocxTool -Arguments @(
    "convert",
    "--zip", $Zip,
    "--main-tex", "main-jos.tex",
    "--page-setup", "jos-paper3",
    "--out", $RustDocx
)

if (-not (Test-Path -LiteralPath $RustDocx)) {
    throw "rust DOCX not generated: $RustDocx"
}
Write-Host "OK $(Split-Path -Leaf $RustDocx)"

$PandocDocx = Join-Path $OutDir "$Base-pandoc.docx"
if (Get-Command pandoc -ErrorAction SilentlyContinue) {
    Write-Host "=== generating pandoc DOCX ==="
    try {
        & (Join-Path $Root "scripts\build_paper3_pandoc_docx.ps1") -Version $VersionTag -Timestamp $Stamp | Out-Null
        if (Test-Path -LiteralPath $PandocDocx) {
            Write-Host "OK $(Split-Path -Leaf $PandocDocx)"
        } else {
            Write-Warning "pandoc DOCX not produced (skipped)"
        }
    } catch {
        Write-Warning "pandoc DOCX generation failed (continuing without it): $_"
    }
} else {
    Write-Warning "pandoc not installed; skipping pandoc DOCX"
}

Write-Host "sh    : $ShDocx ($(Get-FileSizeBytes -Path $ShDocx) bytes)"
Write-Host "rust  : $RustDocx ($(Get-FileSizeBytes -Path $RustDocx) bytes)"
if (Test-Path -LiteralPath $PandocDocx) {
    Write-Host "pandoc: $PandocDocx ($(Get-FileSizeBytes -Path $PandocDocx) bytes)"
} else {
    Write-Host "pandoc: (skipped)"
}

Write-Host "=== done ==="
