#!/usr/bin/env bash
# 生成 paper3 的双版本 DOCX：sh 版 + rust 版。
#
# 输出到：examples/paper3/output/to-docx
# 用法：
#   bash scripts/build_paper3_dual_docx.sh [VERSION] [ZIP]
#
# 说明：
# - sh 版本完全复用 scripts/build_docx.sh 的实现算法（Python build_jos_docx.py
#   + jos_2025_docx_format_definitions.json 模板 + latexmk 编译 PDF/BBL +
#   verify_jos_docx.py 校验）。最终产物名由 build_docx.sh 决定，命名规则为
#   `v${VERSION}-论文稿件-jos-sh-${TS}.docx`，与单跑 build_docx.sh 时一致，
#   并落在 ${OUT_DIR} 下。
# - rust 版本直接由 doc-engine 解析 upload.zip 后产出，文件名为
#   `${BASE}-rust.docx`，其中 BASE = "${VERSION}-论文稿件-jos-${STAMP}"。
# - 若 ZIP 不存在，会从 examples/paper3/latex/main-jos.tex 所在目录自动生成 upload.zip。
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VERSION="${1:-v12}"
PAPER3_DIR="$ROOT/examples/paper3"
LATEX_DIR="$PAPER3_DIR/latex"
MAIN_TEX="$LATEX_DIR/main-jos.tex"
ZIP="${2:-$PAPER3_DIR/upload.zip}"
OUT_DIR="$PAPER3_DIR/output/to-docx"
STAMP="$(date +%Y%m%d-%H%M%S)"
BASE="${VERSION}-论文稿件-jos-${STAMP}"
RUST_DOCX="$OUT_DIR/${BASE}-rust.docx"
DOCX_TOOL="$ROOT/target/release/doc-engine"

mkdir -p "$OUT_DIR"

# sh 版本的产物名由 build_docx.sh 决定：v${VERSION}-论文稿件-jos-sh-${TS}.docx。
# 调用前先记下当前已有的 docx 清单，调用后找出新生成的那个。
sh_before_listing() {
  find "$OUT_DIR" -maxdepth 1 -type f -name 'v*-论文稿件-jos-sh-*.docx' -printf '%f\n' 2>/dev/null | sort
}

echo "=== generating sh DOCX (delegated to scripts/build_docx.sh) ==="
BEFORE_SH="$(sh_before_listing)"
# build_docx.sh 接收版本号作为 $1；它内部会：
#   1) 检查依赖 + 用 sha256 manifest 决定是否重跑 latexmk 编译 PDF/BBL；
#   2) 调用 build_jos_docx.py 生成 docx；
#   3) 调用 verify_jos_docx.py 写出 md + json 校验报告。
bash "$ROOT/scripts/build_docx.sh" "$VERSION"

# 抓取本次新生成的 sh 版 docx 路径。匹配 build_docx.sh 内部的命名规则
# `v${VERSION}-论文稿件-jos-sh-${TS}.docx`。
SH_DOCX="$(find "$OUT_DIR" -maxdepth 1 -type f -name "v${VERSION}-论文稿件-jos-sh-*.docx" \
  -newer "$ROOT/scripts/build_docx.sh" -printf '%T@ %p\n' 2>/dev/null \
  | sort -n | tail -1 | sed 's/^[0-9.]* //')"

if [[ -z "${SH_DOCX:-}" || ! -f "$SH_DOCX" ]]; then
  # 退化路径：上面的 -newer 没匹配到时，直接取最新时间戳的同名文件。
  SH_DOCX="$(find "$OUT_DIR" -maxdepth 1 -type f -name "v${VERSION}-论文稿件-jos-sh-*.docx" \
    -printf '%T@ %p\n' 2>/dev/null | sort -n | tail -1 | sed 's/^[0-9.]* //')"
fi

if [[ -z "${SH_DOCX:-}" || ! -f "$SH_DOCX" ]]; then
  echo "❌ sh DOCX not generated by build_docx.sh" >&2
  exit 1
fi
echo "✓ $(basename "$SH_DOCX") (via build_docx.sh)"

if [[ ! -f "$ZIP" ]]; then
  echo "=== zip not found; building upload.zip from $MAIN_TEX ==="
  if [[ ! -f "$MAIN_TEX" ]]; then
    echo "❌ missing main tex: $MAIN_TEX" >&2
    exit 3
  fi
  ZIP="$PAPER3_DIR/upload.zip"
  python3 - <<PY
from pathlib import Path
from zipfile import ZipFile, ZIP_DEFLATED

latex_dir = Path(r"$LATEX_DIR")
main_tex = Path(r"$MAIN_TEX")
out_zip = Path(r"$ZIP")
keep_suffixes = {".tex", ".bib", ".cls", ".bst", ".sty"}

if not main_tex.is_file():
    raise SystemExit(f"missing main tex: {main_tex}")

files = [p for p in latex_dir.rglob("*") if p.is_file() and p.suffix.lower() in keep_suffixes]
if not files:
    raise SystemExit(f"no tex assets found under: {latex_dir}")

out_zip.parent.mkdir(parents=True, exist_ok=True)
with ZipFile(out_zip, "w", ZIP_DEFLATED) as zf:
    for p in sorted(files):
        zf.write(p, p.relative_to(latex_dir).as_posix())

print(f"[paper3-zip] wrote {out_zip}")
print(f"[paper3-zip] entries = {len(files)}")
PY
fi

command -v cargo >/dev/null 2>&1 || { echo "❌ missing: cargo (needed to build doc-engine for rust DOCX)" >&2; exit 3; }

if [[ ! -x "$DOCX_TOOL" ]]; then
  echo "=== building doc-engine (release) ==="
  (cd "$ROOT" && cargo build --release -p doc-engine)
fi

if [[ ! -x "$DOCX_TOOL" ]]; then
  echo "❌ missing tool: $DOCX_TOOL" >&2
  exit 3
fi

echo "=== generating rust DOCX ==="
"$DOCX_TOOL" convert \
  --zip "$ZIP" \
  --main-tex main-jos.tex \
  --page-setup jos-paper3 \
  --out "$RUST_DOCX"

if [[ ! -f "$RUST_DOCX" ]]; then
  echo "❌ rust DOCX not generated: $RUST_DOCX" >&2
  exit 1
fi
echo "✓ $(basename "$RUST_DOCX")"

python3 - <<PY
from pathlib import Path
sh = Path(r"$SH_DOCX")
rust = Path(r"$RUST_DOCX")
print(f"sh  : {sh} ({sh.stat().st_size} bytes)")
print(f"rust: {rust} ({rust.stat().st_size} bytes)")
PY

echo "=== done ==="
